name: Find Branch
on:
  push:
    tags:
      - v*
jobs:
  getBranchName:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - run: echo $(git symbolic-ref --short HEAD)
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo ${{ steps.extract_branch.outputs.branch }}
  releaseCode:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - run: sleep 4
  bumpDepsOnlyIfMain:
    runs-on: ubuntu-latest
    needs: releaseCode
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo BRANCH=$branch >> $GITHUB_ENV
      - run: echo ${{ env.BRANCH }}
      - name: if step
        if: ${{ contains(env.BRANCH, 'main')}}
        run: sleep 4
