name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  releaseCode:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v2
      - name: alwaysRun
        run: sleep 4
  bumpDepsOnlyIfMain:
    runs-on: ubuntu-latest
    needs: releaseCode
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Get Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo BRANCH=$branch >> $GITHUB_ENV
      - run: echo ${{ env.BRANCH }}
      - name: if step
        if: ${{ contains(env.BRANCH, 'main')}}
        run: sleep 4
