name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git branch --show-current
      - name: Get Branch
        - run: |
            raw=$(git branch -r --contains ${{ github.ref }})
            branch=${raw/origin\/}
            echo ::set-env name=BRANCH::$branch
        - run: echo ${{ env.BRANCH }}
      - name: Pause always
        run: sleep 6
      - name: Pause - only main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: sleep 9
